#!/bin/sh

	export TERM=vt100
	PID=$(/usr/bin/cat /var/sf/run/SFDataCorrelator.pid)
	/usr/bin/echo "========================"
	/usr/bin/top -b -p $PID -n 1
	/var/tmp/remap_vulns.pl
	/usr/bin/top -b -p $PID -n 1
	/usr/bin/echo
