package virii;

require Exporter;
@ISA	= qw( Exporter );
@EXPORT	= qw( %mime_virus %uu_virus %Key $BubbleBoy $wmt_clean_digest
	      %Contents %VirusFile %Digest );

%mime_virus = ( WMT => q@Content-Type: application/msword;
	name="WMTestMacro.doc"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
	filename="WMTestMacro.doc"

0M8R4KGxGuEAAAAAAAAAAAAAAAAAAAAAPgADAP7/CQAGAAAAAAAAAAAAAAABAAAADAAAAAAA
AAAAEAAADwAAAAEAAAD+////AAAAAA0AAAD/////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
///////////////////////////////////9////BQAAAP7///8EAAAABgAAAP7///8HAAAA
CAAAAAkAAAAKAAAACwAAAP7/////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////1IA
bwBvAHQAIABFAG4AdAByAHkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAWAAUA//////////8DAAAAAAkCAAAAAADAAAAAAAAARgAAAAAAAAAAAAAAAABQ
ZbPxfrsBAwAAAMAOAAAAAAAAAQBDAG8AbQBwAE8AYgBqAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIAAgH///////////////8AAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbgAAAAAAAABXAG8AcgBkAEQAbwBjAHUA
bQBlAG4AdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGgACAf//
//8EAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAABpCwAA
AAAAAE8AYgBqAGUAYwB0AFAAbwBvAGwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAWAAEBAQAAAAIAAAD/////AAAAAAAAAAAAAAAAAAAAAAAAAACAljqz
8X67AYCWOrPxfrsBAAAAAAAAAAAAAAAAAQAAAP7///8DAAAABAAAAAUAAAAGAAAABwAAAAgA
AAAJAAAACgAAAAsAAAAMAAAADQAAAA4AAAAaAAAAEAAAABEAAAASAAAAEwAAABQAAAAVAAAA
FgAAABcAAAAYAAAAGQAAAP7///8bAAAAHAAAAB0AAAAeAAAAHwAAACAAAAAhAAAAIgAAACMA
AAAkAAAAJQAAACYAAAAnAAAAKAAAACkAAAAqAAAAKwAAACwAAAAtAAAALgAAAC8AAAAwAAAA
MQAAADIAAAAzAAAANAAAADUAAAA2AAAANwAAADgAAAA5AAAAOgAAAP7/////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////8BAP7/
AwoAAP////8ACQIAAAAAAMAAAAAAAABGHAAAAE1pY3Jvc29mdCBXb3JkIDYuMCBEb2N1bWVu
dAAKAAAATVNXb3JkRG9jABAAAABXb3JkLkRvY3VtZW50LjYA9DmycQAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAANylZQAtwAkIAAABAGUAAAAAAAAAAAAAAAADAAABAwAAaQsAAAAA
AAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAA
agAAAAAIAABqAAAAaggAAAAAAABqCAAAAAAAAGoIAAAAAAAAaggAAAAAAABqCAAAFAAAAJQI
AAAAAAAAlAgAAAAAAACUCAAAAAAAAJQIAAAAAAAAlAgAAAAAAACUCAAACgAAAJ4IAAAKAAAA
lAgAAAAAAAC8CgAAMQAAAKgIAAAAAAAAqAgAAAAAAACoCAAAAAAAAKgIAAAAAAAAqAgAAAAA
AACoCAAAAAAAAKgIAAAAAAAAqAgAAAAAAADICAAAAgAAAMoIAAAAAAAAyggAAAAAAADKCAAA
LAAAAPYIAADUAAAAygkAANQAAACeCgAAHgAAAO0KAABUAAAAQQsAACgAAAC8CgAAAAAAAAAA
AAAAAAAAAAAAAAAAAABqCAAAAAAAAKgIAAAAAAAAAAACAAMAAQABAKgIAAAAAAAAqAgAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAqAgAAAAAAACoCAAAAAAAALwKAAAAAAAAqAgAAAAAAABqCAAA
AAAAAGoIAAAAAAAAqAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqAgAAAAAAACoCAAAAAAAAKgI
AAAAAAAAqAgAAAAAAACoCAAAAAAAAGoIAAAAAAAAqAgAAAAAAABqCAAAAAAAAKgIAAAAAAAA
yAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfggAAAgAAACGCAAADgAAAGoIAAAAAAAAaggAAAAA
AABqCAAAAAAAAGoIAAAAAAAAqAgAAAAAAADICAAAAAAAAKgIAAAgAAAAqAgAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0GAKSCLqXGQQAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+/wAAA18AAAAAAAAAAAAA
AAAAAAAAAAABAAAA4IWf8vlPaBCrkQgAKyez2TAAAABsAgAADQAAAAcAAACYAAAABQBTAHUA
bQBtAGEAcgB5AEkAbgBmAG8AcgBtAGEAdABpAG8AbgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAACgAAgD///////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAPAAAAnAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////////////wAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////
////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAD///////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAvAAAAAgAAADgAAAADAAAAAQBAAALAAAAKAEAAA0A
AABMAQAADwAAAHABAAAQAAAAlAEAAAoAAAC4AQAAEgAAANwBAAAOAAAAAAIAAAkAAAAkAgAA
EwAAAEgCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgAAABYA
AABDOlxXSU5XT1JEXE5PUk1BTC5ET1QAAAAAAAAAHgAAAAsAAABMLiBTdGFubGV5AAAAAAAA
AAAAAAAAAAAAAAAAHgAAAAsAAABMLiBTdGFubGV5AAAAAAAAAAAAAAAAAAAAAAAAQAAAAABe
kgb6frsBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAADApFmLt94BAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAQAAAAABekgb6frsBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAQAAAAABGwyMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgAAABMA
AABNaWNyb3NvZnQgV29yZCA2LjAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAHgAAAAIAAAAxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAEDAAAJAwAA
AP4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAJ1AQIAAwAAAQMAAP4AAXAg8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAQ4ADwAIAAEASwAPAAAA
AAAaAABA8f8CABoABk5vcm1hbAACAAAAAwBhCQgAAAAAAAAAAAAAAAAAAAAAAAAAIgBBQPL/
oQAiABZEZWZhdWx0IFBhcmFncmFwaCBGb250AAAAAAAAAAAAAAAAAAAAAQAAAAQAAQMAAAAA
/////wEABCD//wEAAAAAAAEAAAAAAAAAAAAAAwAACQMAAAIAAAMAAAEDAAADACAACkwuIFN0
YW5sZXkSQzpcUFJfNzYzXERPQzIuRE9U/0BIUCBMYXNlckpldCBJSUkAXFxQYXJzbGV5XG1h
bnVlbF8xAEhQUENMNU1TAEhQIExhc2VySmV0IElJSQAAAAAAAAAAAAAAAAAAAAAAAAQBBJQA
QAADZwAEAQAJAAAAAAAAAAEAAQAsAQEAAQAsAQIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAA
AAABAEAATVNVRE4DSFAgTGFzZXJKZXQgSUlJAAAAAAAAAAAAAAAAAAAAAACgAQAAAAAAAAAA
AAAAAAAAZAAKAAAASFAgTGFzZXJKZXQgSUlJAAAAAAAAAAAAAAAAAAAAAAAABAEElABAAANn
AAQBAAkAAAAAAAAAAQABACwBAQABACwBAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAEA
QABNU1VETgNIUCBMYXNlckpldCBJSUkAAAAAAAAAAAAAAAAAAAAAAKABAAAAAAAAAAAAAAAA
AABkAAoAAAAAgAEAAAAAAAAAAAAHAACAAAAAAAAAAAAAAAAAAAAxABUWkAEAAFRpbWVzIE5l
dyBSb21hbgAMFpABAgBTeW1ib2wACyaQAQAAQXJpYWwAIgAEAAEIiBgAANACAABoAQAAAAAF
/AdmBfwHZgAAAAABAAEAAAAAAAAAAAAAAAAAAAAAAAQAgxAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAACQDKAAAAAAAAAAKTC4gU3RhbmxleQpMLiBTdGFubGV5AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABSAG8AbwB0ACAARQBuAHQAcgB5AAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFgAFAP//////////AwAAAAAJAgAAAAAAwAAAAAAA
AEYAAAAAQIk3s/F+uwEANq/Y8X67ARQAAAAADwAAAAAAAAEAQwBvAG0AcABPAGIAagAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASAAIB////////
////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG4AAAAAAAAA
VwBvAHIAZABEAG8AYwB1AG0AZQBuAHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAABoAAgH/////BAAAAP////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAACAAAAtgsAAAAAAABPAGIAagBlAGMAdABQAG8AbwBsAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFgABAQEAAAACAAAA/////wAAAAAAAAAA
AAAAAAAAAAAAAAAAgJY6s/F+uwGAljqz8X67AQAAAAAAAAAAAAAAAP//////////////////
/////////////////////////////////////////////w4AAAD9/////v////7///8VAAAA
EgAAABAAAAD+////EQAAABYAAAAXAAAAEwAAAP//////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////BQBTAHUAbQBtAGEAcgB5AEkAbgBmAG8AcgBtAGEAdABpAG8AbgAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAgD///////////////8AAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAAnAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////////
/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////////////8AAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAA/v///wMAAAAEAAAA
BQAAAAYAAAAHAAAACAAAAAkAAAAKAAAACwAAAAwAAAANAAAADgAAABoAAAAQAAAAEQAAABIA
AAATAAAAFAAAABUAAAAWAAAAFwAAABgAAAAZAAAA/v///xsAAAAcAAAAHQAAAB4AAAAfAAAA
IAAAACEAAAAiAAAAIwAAACQAAAAlAAAAJgAAACcAAAAoAAAAKQAAACoAAAArAAAALAAAAC0A
AAAuAAAALwAAADAAAAAxAAAAMgAAADMAAAA0AAAANQAAADYAAAA3AAAAOAAAADkAAAA6AAAA
OwAAAP7/////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
/////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAHgAAAAIAAAAyAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAMAAAEDAAAJAwAAIwMAAAD+/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqAgAAAAAAAAAAAIAAwABAAEA
qAgAAAAAAACoCAAAAAAAAAAAAAAAAAAAAAAAAAAAAACoCAAAAAAAAKgIAAAAAAAA9AoAAAAA
AACoCAAAAAAAAGoIAAAAAAAAaggAAAAAAACoCAAAAAAAAAAAAAAAAAAAAAAAAAAAAACoCAAA
AAAAAKgIAAAAAAAAqAgAAAAAAACoCAAAAAAAAKgIAAAAAAAAaggAAAAAAACoCAAAAAAAAGoI
AAAAAAAAqAgAAAAAAADICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB+CAAACAAAAIYIAAAOAAAA
aggAAAAAAABqCAAAAAAAAGoIAAAAAAAAaggAAAAAAACoCAAAAAAAAMgIAAAAAAAAqAgAACAA
AACoCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADQYApIIupcZBAQBk
G2kETUFJTmRwCiBaUVpYSlZCVlRkGhsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP7/
AAADXwAAAAAAAAAAAAAAAAAAAAAAAAEAAADghZ/y+U9oEKuRCAArJ7PZMAAAAGwCAAANAAAA
BwAAAJgAAAAEAAAAvAAAAAgAAADgAAAADAAAAAQBAAALAAAAKAEAAA0AAABMAQAADwAAAHAB
AAAQAAAAlAEAAAoAAAC4AQAAEgAAANwBAAAOAAAAAAIAAAkAAAAkAgAAEwAAAEgCAADgE8hw
hu7NZ1jYRSMOeVWKeGAkHg854ojuttSz2UX2C/DqXa6r+LehHgAAABYAAABDOlxXSU5XT1JE
XE5PUk1BTC5ET1QAAAAAAAAAHgAAAAsAAABMLiBTdGFubGV5AAAAAAAAAAAAAAAAAAAAAAAA
HgAAAAsAAABMLiBTdGFubGV5AAAAAAAAAAAAAAAAAAAAAAAAQAAAAABekgb6frsBAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAQAAAAADApFmLt94BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
QAAAAACkVSr6frsBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
QAAAAACMhkcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgAAABMAAABNaWNyb3NvZnQg
V29yZCA2LjAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAKABAAAAAAAAAAAAAAAAAABkAAoA
AAAAgAEAAAAAAAAAAAAHAACAAIAAAAAAAAAAAAAAAAACEAAAAAAAAAABAAAAAAQAAwAAAAAx
ABUWkAEAAFRpbWVzIE5ldyBSb21hbgAMFpABAgBTeW1ib2wACyaQAQAAQXJpYWwAIgAEAAEI
iBgAANACAABoAQAAAAAF/AdmBvwHZgAAAAACAAIAAAAAAAAAAAAAAAAAAAAAAAQAgxAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAACQDKAAAAAAAAAAKTC4gU3RhbmxleQpMLiBTdGFubGV5
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAQD+/wMKAAD/////AAkCAAAAAADAAAAAAAAARhwAAABNaWNyb3NvZnQgV29yZCA2
LjAgRG9jdW1lbnQACgAAAE1TV29yZERvYwAQAAAAV29yZC5Eb2N1bWVudC42APQ5snEAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADcpWUALcAJCAAAFQBlAAAAAAAAAAAAAAAAAwAA
AQMAALYLAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAgAAGoAAAAACAAAagAAAGoIAAAAAAAAaggAAAAAAABqCAAAAAAAAGoIAAAAAAAA
aggAABQAAACUCAAAAAAAAJQIAAAAAAAAlAgAAAAAAACUCAAAAAAAAJQIAAAAAAAAlAgAAAoA
AACeCAAACgAAAJQIAAAAAAAACQsAADEAAACoCAAAAAAAAKgIAAAAAAAAqAgAAAAAAACoCAAA
AAAAAKgIAAAAAAAAqAgAAAAAAACoCAAAAAAAAKgIAAAAAAAAyAgAADoAAAACCQAAAAAAAAIJ
AAAAAAAAAgkAACwAAAAuCQAA1AAAAAIKAADUAAAA1goAAB4AAAA6CwAAVAAAAI4LAAAoAAAA
9AoAABUAAAAAAAAAAAAAAAAAAAAAAAAAaggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnUBAwADAAABAwAA/gABcCDwAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAB
DgAPAAgAAQBLAA8AAAAAABoAAEDx/wIAGgAGTm9ybWFsAAIAAAADAGEJCAAAAAAAAAAAAAAA
AAAAAAAAAAAiAEFA8v+hACIAFkRlZmF1bHQgUGFyYWdyYXBoIEZvbnQAAAAAAAAAAAAAAAAA
AAABAAAABAABAwAABAD/////AQAEIP//AQAAAAAAAQAAAAAAAAAAAAADAAAjAwAAAgAAAwAA
AQMAAAMAIAAKTC4gU3RhbmxleRJDOlxQUl83NjNcRE9DMi5ET1T/AQEAVQAAAAAA//8AAAAA
GgAAAAgAAAAJAwAAEA0ACFRSWUdVQVJEAQARAQAAAAhUUllHVUFSRABASFAgTGFzZXJKZXQg
SUlJAFxcUGFyc2xleVxtYW51ZWxfMQBIUFBDTDVNUwBIUCBMYXNlckpldCBJSUkAAAAAAAAA
AAAAAAAAAAAAAAAEAQSUAEAAA2cABAEACQAAAAAAAAABAAEALAEBAAEALAECAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAgAAAAAAAAAAAAAAAQBAAE1TVUROA0hQIExhc2VySmV0IElJSQAAAAAAAAAAAAAA
AAAAAAAAoAEAAAAAAAAAAAAAAAAAAGQACgAAAEhQIExhc2VySmV0IElJSQAAAAAAAAAAAAAA
AAAAAAAAAAQBBJQAQAADZwAEAQAJAAAAAAAAAAEAAQAsAQEAAQAsAQIAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAACAAAAAAAAAAAAAAABAEAATVNVRE4DSFAgTGFzZXJKZXQgSUlJAAAAAAAAAAAAAAAAAAAA
AAA=
@,

              clean => q@Content-Type: application/msword;
	name="clean.doc"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
	filename="clean.doc"

0M8R4KGxGuEAAAAAAAAAAAAAAAAAAAAAPgADAP7/CQAGAAAAAAAAAAAAAAABAAAAIQAAAAAA
AAAAEAAAIwAAAAEAAAD+////AAAAACAAAAD/////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
///////////////////////////////////spcEAWQAJBAAAABK/AAAAAAAAEAAAAAAABAAA
AQQAAA4AYmpiavNX81cAAAAAAAAAAAAAAAAAAAAAAAAJBBYAHgwAAJE9AQCRPQEAAQAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//w8AAAAAAAAAAAD//w8AAAAAAAAAAAD//w8A
AAAAAAAAAAAAAAAAAAAAAF0AAAAAAJIAAAAAAAAAkgAAAJIAAAAAAAAAkgAAAAAAAACSAAAA
AAAAAJIAAAAAAAAAkgAAABQAAAAAAAAAAAAAAKYAAAAAAAAApgAAAAAAAACmAAAAAAAAAKYA
AAAAAAAApgAAAAwAAACyAAAADAAAAKYAAAAAAAAALQEAALYAAADKAAAAAAAAAMoAAAAAAAAA
ygAAAAAAAADKAAAAAAAAAMoAAAAAAAAAygAAAAAAAADKAAAAAAAAAMoAAAAAAAAA8gAAAAIA
AAD0AAAAAAAAAPQAAAAAAAAA9AAAAAAAAAD0AAAAAAAAAPQAAAAAAAAA9AAAACQAAADjAQAA
9AEAANcDAAA2AAAAGAEAABUAAAAAAAAAAAAAAAAAAAAAAAAAkgAAAAAAAADKAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAADKAAAAAAAAAMoAAAAAAAAAygAAAAAAAADKAAAAAAAAABgBAAAAAAAA
ygAAAAAAAACSAAAAAAAAAJIAAAAAAAAAygAAAAAAAAAAAAAAAAAAAMoAAAAAAAAAygAAAAAA
AADKAAAAAAAAAMoAAAAAAAAAygAAAAAAAADKAAAAAAAAAJIAAAAAAAAAygAAAAAAAACSAAAA
AAAAAMoAAAAAAAAA8gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApgAAAAAAAACmAAAAAAAAAJIA
AAAAAAAAkgAAAAAAAACSAAAAAAAAAJIAAAAAAAAAygAAAAAAAADyAAAAAAAAAMoAAAAoAAAA
ygAAAAAAAAAAAAAAAAAAAPIAAAAAAAAAkgAAAAAAAACSAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8gAAAAAAAADKAAAA
AAAAAL4AAAAMAAAAkLx+b2ohvwGmAAAAAAAAAKYAAAAAAAAAygAAAAAAAADyAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAA
AQQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAEAAABBAAA/QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAQAAAEE
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAEcAB+w0C8gsOA9IbAIByKwCAcjkKAFJJCgBSWwAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAEgAPAAoAAQBbAA8AAgAAAAAAAAAkAABA8f8CACQAAAAGAE4A
bwByAG0AYQBsAAAAAgAAAAQAbUgJBAAAAAAAAAAAAAAAAAAAAAAAADwAQUDy/6EAPAAAABYA
RABlAGYAYQB1AGwAdAAgAFAAYQByAGEAZwByAGEAcABoACAARgBvAG4AdAAAAAAAAAAAAAAA
AAAAAAAAAQAAAAQAAAwAAAAA/////wAEAAABBAAAAwAAAAAEAAABBAAABAAAAAAEAAABBAAA
BQAAAP//AgAAAAMATgBBAEkADABDADoAXABDAGwAZQBhAG4ALgBkAG8AYwD/QACAAQAAAAAA
AAAAAHim6gABAAAAAAAAAAAAAAAAAAAAAAAAAAIQAAAAAAAAAAEAAABAAAAIAEAAAAMAAABH
FpABAAACAgYDBQQFAgMEhwIAAAAAAAAAAAAAAAAAAJ8AAAAAAAAAVABpAG0AZQBzACAATgBl
AHcAIABSAG8AbQBhAG4AAAA1FpABAgAFBQECAQcGAgUHAAAAAAAAABAAAAAAAAAAAAAAAIAA
AAAAUwB5AG0AYgBvAGwAAAAzJpABAAACCwYEAgICAgIEhwIAAAAAAAAAAAAAAAAAAJ8AAAAA
AAAAQQByAGkAYQBsAAAAIgAEADEIiBgAANACAABoAQAAAABg4zqGYOM6hgAAAAABAAAAAAAA
AAAAAAAAAAEAAQAAAAQAAxABAAAAAAAAAAAAAAABAAEAAAABAAAAAAAAACQDAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKUGwAe0ALQAgAASMAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAD//xIAAAAAAAAAAAAAAAAAAAADAE4AQQBJ
AAMATgBBAEkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAP7/AAAEAAIAAAAAAAAAAAAAAAAAAAAAAAEAAADghZ/y+U9oEKuRCAArJ7PZ
MAAAAEwBAAAQAAAAAQAAAIgAAAACAAAAkAAAAAMAAACcAAAABAAAAKgAAAAFAAAAtAAAAAcA
AADAAAAACAAAANQAAAAJAAAA4AAAABIAAADsAAAACgAAAAgBAAAMAAAAFAEAAA0AAAAgAQAA
DgAAACwBAAAPAAAANAEAABAAAAA8AQAAEwAAAEQBAAACAAAA5AQAAB4AAAABAAAAAABzAB4A
AAABAAAAAABzAB4AAAAEAAAATkFJAB4AAAABAAAAAEFJAB4AAAALAAAATm9ybWFsLmRvdAAA
HgAAAAQAAABOQUkAHgAAAAIAAAAxAEkAHgAAABMAAABNaWNyb3NvZnQgV29yZCA4LjAAAEAA
AAAAAAAAAAAAAEAAAAAAKAdXaiG/AUAAAAAAKAdXaiG/AQMAAAABAAAAAwAAAAAAAAADAAAA
AAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAD+/wAABAACAAAAAAAAAAAAAAAAAAAAAAACAAAAAtXN1ZwuGxCTlwgAKyz5rkQAAAAF1c3V
nC4bEJOXCAArLPmuLAEAAOgAAAAMAAAAAQAAAGgAAAAPAAAAcAAAAAUAAAB8AAAABgAAAIQA
AAARAAAAjAAAABcAAACUAAAACwAAAJwAAAAQAAAApAAAABMAAACsAAAAFgAAALQAAAANAAAA
vAAAAAwAAADJAAAAAgAAAOQEAAAeAAAABAAAAE5BSQADAAAAAQAAAAMAAAABAAAAAwAAAAAA
AAADAAAAahAIAAsAAAAAAAAACwAAAAAAAAALAAAAAAAAAAsAAAAAAAAAHhAAAAEAAAABAAAA
AAwQAAACAAAAHgAAAAYAAABUaXRsZQADAAAAAQAAAACYAAAAAwAAAAAAAAAgAAAAAQAAADYA
AAACAAAAPgAAAAEAAAACAAAACgAAAF9QSURfR1VJRAACAAAA5AQAAEEAAABOAAAAewBBAEQA
MgAyAEUAQgA1ADAALQA4AEQANQBEAC0AMQAxAEQAMwAtADgAMgBFADEALQAwADAANQAwADAA
NABBADIANQAwADEANAB9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAIA
AAADAAAABAAAAAUAAAAGAAAABwAAAP7///8JAAAACgAAAAsAAAAMAAAADQAAAA4AAAAPAAAA
/v///xEAAAASAAAAEwAAABQAAAAVAAAAFgAAABcAAAD+////GQAAABoAAAAbAAAAHAAAAB0A
AAAeAAAAHwAAAP7////9////IgAAAP7////+/////v//////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
//////////////////////////9SAG8AbwB0ACAARQBuAHQAcgB5AAAAAADAGtpLAwm/AdDb
ew1qIb8BoLYSzcggvwEAAAAAAAAAAAAAAAAAAAAAFgAFAf//////////AwAAAAYJAgAAAAAA
wAAAAAAAAEYAAAAAsCNXb2ohvwGArI9vaiG/ASQAAACAAAAAAAAAADEAVABhAGIAbABlAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAIA
////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAQ
AAAAAAAAVwBvAHIAZABEAG8AYwB1AG0AZQBuAHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAABoAAgEFAAAA//////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAFAFMAdQBtAG0AYQByAHkASQBuAGYAbwByAG0A
YQB0AGkAbwBuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAACAQIAAAAEAAAA/////wAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAEAAAAAAAAAUARABvAGMA
dQBtAGUAbgB0AFMAdQBtAG0AYQByAHkASQBuAGYAbwByAG0AYQB0AGkAbwBuAAAAAAAAAAAA
AAA4AAIB////////////////SABJAH4AMQAAAEQATwBUAAAAAAAAAAAAJp0bCAAAAAAYPxYA
GAAAAAAQAAAAABYAAQBDAG8AbQBwAE8AYgBqAAAAAAAAAAAAAAABAEEAAAAAAAAAAAAAAAAA
AAD/////AAAAAAAAAAAAAAAAAAAAABIAAgEBAAAABgAAAP////8AAAAAAAAAAAAAAAAAAAAA
SAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAagAAAD8AXABPAGIAagBlAGMAdABQAG8AbwBsAAAA
XABkAGUAcwBrAHQAbwBwAC4AaQBuAGkAAAAAAAAAAAAAAAAAAAAAAAAAFgABAP//////////
/////wAAAAAAAAAAAAAAAAAAAAAAAAAAgKyPb2ohvwGArI9vaiG/AQAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAQAAAP7/////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////8BAP7/AwoAAP//
//8GCQIAAAAAAMAAAAAAAABGGAAAAE1pY3Jvc29mdCBXb3JkIERvY3VtZW50AAoAAABNU1dv
cmREb2MAEAAAAFdvcmQuRG9jdW1lbnQuOAD0ObJxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA==
@,

              eicar_tgz => q@Content-Type: application/x-compressed;
	name="eicar_tgz"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
	filename="eicar_tgz"

H4sICJ/z/TcAA2VpY2FyLnRhcgDtz8EKgkAUhWEf5QoGWRgjzTjbBjMSwkQtpCIIadEigva9e0W9
grTo/zbnclbnni/d6T7pblevP7FSSaLFE5FYf1JEffNdKi2SWKONjafKvprXYTzpcRK+WrP2y8HM
lXt9KHet0cPyGNo0De0jyPLUVVHduGLuqnnkiibf5tWmjpqsbqJFvsr8YDlejn79AwAAAAAAAAAA
AAAAAAD8oycbcSILACgAAA==
@,

              eicar_zip => q@Content-Type: application/x-zip-compressed;
	name="eicar.zip"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
	filename="eicar.zip"

UEsDBAoAAAAAAG951SY8z1FoRAAAAEQAAAAJAAAAZWljYXIuY29tWDVPIVAlQEFQWzRcUFpYNTQo
UF4pN0NDKTd9JEVJQ0FSLVNUQU5EQVJELUFOVElWSVJVUy1URVNULUZJTEUhJEgrSCpQSwECFAAK
AAAAAABvedUmPM9RaEQAAABEAAAACQAAAAAAAAABACAA/4EAAAAAZWljYXIuY29tUEsFBgAAAAAB
AAEANwAAAGsAAAAAAA==
@,

              eicar => 'Content-Type: application/octet-stream;
	name="eicar.com"
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment;
	filename="eicar.com"

X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*',

              no_name => 'Content-Type: application/octet-stream;
	name=""
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment;
	filename=""

X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*',

              eicar_xyz => 'Content-Type: application/octet-stream;
	name="eicar.xyz"
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment;
	filename="eicar.xyz"

X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*',

              null => '',
);

%uu_virus = ( WMT => q~begin 644 WMTestMacro.doc
MT,\1X*&Q&N$`````````````````````/@`#`/[_"0`&```````````````!
M````# ``````````$ ``#P````$```#^____``````T```#_____________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M_______________________]____!0```/[___\$````!@```/[___\'````
M" ````D````*````"P```/[_____________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M_____________________________________________U(`;P!O`'0`( !%
M`&X`= !R`'D`````````````````````````````````````````````````
M```````````6``4`__________\#``````D"``````# ````````1@``````
M``````````!09;/Q?KL!`P```, .`````````0!#`&\`;0!P`$\`8@!J````
M````````````````````````````````````````````````````````````
M`!(``@'_______________\`````````````````````````````````````
M````````````````;@````````!7`&\`<@!D`$0`;P!C`'4`;0!E`&X`= ``
M````````````````````````````````````````````````````&@`"`?__
M__\$````_____P``````````````````````````````````````````````
M``(```!I"P```````$\`8@!J`&4`8P!T`% `;P!O`&P`````````````````
M```````````````````````````````````````````6``$!`0````(```#_
M____``````````````````````````" ECJS\7Z[`8"6.K/Q?KL!````````
M`````````0```/[___\#````! ````4````&````!P````@````)````"@``
M``L````,````#0````X````:````$ ```!$````2````$P```!0````5````
M%@```!<````8````&0```/[___\;````' ```!T````>````'P```" ````A
M````(@```",````D````)0```"8````G````* ```"D````J````*P```"P`
M```M````+@```"\````P````,0```#(````S````- ```#4````V````-P``
M`#@````Y````.@```/[_________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M______________________________\!`/[_`PH``/____\`"0(``````, `
M``````!&' ```$UI8W)O<V]F="!7;W)D(#8N,"!$;V-U;65N= `*````35-7
M;W)D1&]C`! ```!7;W)D+D1O8W5M96YT+C8`]#FR<0``````````````````
M`````````````````````-RE90`MP D(```!`&4````````````````#```!
M`P``:0L````````````````````````!````````````````````````````
M````````````````````" ``:@`````(``!J````:@@```````!J" ``````
M`&H(````````:@@```````!J" ``% ```)0(````````E @```````"4" ``
M`````)0(````````E @```````"4" ``"@```)X(```*````E @```````"\
M"@``,0```*@(````````J @```````"H" ```````*@(````````J @`````
M``"H" ```````*@(````````J @```````#(" ```@```,H(````````R@@`
M``````#*" ``+ ```/8(``#4````R@D``-0```">"@``'@```.T*``!4````
M00L``"@```"\"@````````````````````````````!J" ```````*@(````
M```````"``,``0`!`*@(````````J @`````````````````````````````
MJ @```````"H" ```````+P*````````J @```````!J" ```````&H(````
M````J @`````````````````````````````J @```````"H" ```````*@(
M````````J @```````"H" ```````&H(````````J @```````!J" ``````
M`*@(````````R @`````````````````````````````?@@```@```"&" ``
M#@```&H(````````:@@```````!J" ```````&H(````````J @```````#(
M" ```````*@(```@````J @`````````````````````````````````````
M````````````````````````````````````````````````````````````
M``````````````````````````T&`*2"+J7&00``````````````````````
M``````````````````````````````````````````````````#^_P```U\`
M```````````````````````!````X(6?\OE/:!"KD0@`*R>SV3 ```!L`@``
M#0````<```"8````!0!3`'4`;0!M`&$`<@!Y`$D`;@!F`&\`<@!M`&$`= !I
M`&\`;@```````````````````````````````````"@``@#_____________
M__\````````````````````````````````````````````````/````G (`
M````````````````````````````````````````````````````````````
M`````````````````````````````````````/_______________P``````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````________________````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M``````````````````#_______________\`````````````````````````
M```````````````````````````````````````$````O ````@```#@````
M# ````0!```+````* $```T```!,`0``#P```' !```0````E $```H```"X
M`0``$@```-P!```.``````(```D````D`@``$P```$@"````````````````
M````````````````````````````````````````'@```!8```!#.EQ724Y7
M3U)$7$Y/4DU!3"Y$3U0`````````'@````L```!,+B!3=&%N;&5Y````````
M````````````````'@````L```!,+B!3=&%N;&5Y````````````````````
M````0 ````!>D@;Z?KL!````````````````````````````````0 ````# 
MI%F+M]X!````````````````````````````````0 ````!>D@;Z?KL!````
M`````````````````````````````P``````````````````````````````
M`````````````````P``````````````````````````````````````````
M````0 ````!&PR,`````````````````````````````````````'@```!,`
M``!-:6-R;W-O9G0@5V]R9" V+C ``````````````P``````````````````
M````````````````````````````'@````(````Q````````````````````
M`````````````````P``````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M``````````,```$#```)`P```/X`````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M``````````````````````````)U`0(``P```0,``/X``7 @\ ``````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M`````````````````````````````````````````````````0```0X`#P`(
M``$`2P`/```````:``! \?\"`!H`!DYO<FUA; `"`````P!A"0@`````````
M````````````````(@!!0/+_H0`B`!9$969A=6QT(%!A<F%G<F%P:"!&;VYT
M`````````````````````0````0``0,`````_____P$`!"#__P$```````$`
M`````````````P``"0,```(```,```$#```#`" `"DPN(%-T86YL97D20SI<
M4%)?-S8S7$1/0S(N1$]4_T!(4"!,87-E<DIE="!)24D`7%Q087)S;&5Y7&UA
M;G5E;%\Q`$A04$-,-4U3`$A0($QA<V5R2F5T($E)20``````````````````
M``````0!!)0`0 `#9P`$`0`)``````````$``0`L`0$``0`L`0(`````````
M````````````````````````````````````````````````````````````
M```````````````````````"```````````````!`$ `35-51$X#2% @3&%S
M97)*970@24E)``````````````````````"@`0``````````````````9 `*
M````2% @3&%S97)*970@24E)````````````````````````! $$E ! ``-G
M``0!``D``````````0`!`"P!`0`!`"P!`@``````````````````````````
M````````````````````````````````````````````````````````````
M``````(```````````````$`0 !-4U5$3@-(4"!,87-E<DIE="!)24D`````
M`````````````````* !``````````````````!D``H`````@ $`````````
M```'``" ```````````````````Q`!46D $``%1I;65S($YE=R!2;VUA;@`,
M%I !`@!3>6UB;VP`"R:0`0``07)I86P`(@`$``$(B!@``- "``!H`0`````%
M_ =F!?P'9@`````!``$```````````````````````0`@Q `````````````
M`````````````````````"0#* `````````*3"X@4W1A;FQE>0I,+B!3=&%N
M;&5Y````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M``````````````````````````````````````````````````````!2`&\`
M;P!T`" `10!N`'0`<@!Y````````````````````````````````````````
M````````````````````%@`%`/__________`P`````)`@``````P ``````
M`$8`````0(DWL_%^NP$`-J_8\7Z[`10`````#P````````$`0P!O`&T`< !/
M`&(`:@``````````````````````````````````````````````````````
M```````````2``(!________________````````````````````````````
M`````````````````````````&X`````````5P!O`'(`9 !$`&\`8P!U`&T`
M90!N`'0`````````````````````````````````````````````````````
M`!H``@'_____! ```/____\`````````````````````````````````````
M```````````"````M@L```````!/`&(`:@!E`&,`= !0`&\`;P!L````````
M````````````````````````````````````````````````````%@`!`0$`
M```"````_____P``````````````````````````@)8ZL_%^NP& ECJS\7Z[
M`0```````````````/__________________________________________
M_____________________PX```#]_____O____[___\5````$@```! ```#^
M____$0```!8````7````$P```/__________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M________________________________________!0!3`'4`;0!M`&$`<@!Y
M`$D`;@!F`&\`<@!M`&$`= !I`&\`;@``````````````````````````````
M`````"@``@#_______________\`````````````````````````````````
M```````````````/````G (`````````````````````````````````````
M````````````````````````````````````````````````````````````
M`/_______________P``````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````________
M________````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M``````````````````````````````````````````#_______________\`
M````````````````````````````````````````````````````````````
M```!````_O___P,````$````!0````8````'````" ````D````*````"P``
M``P````-````#@```!H````0````$0```!(````3````% ```!4````6````
M%P```!@````9````_O___QL````<````'0```!X````?````( ```"$````B
M````(P```"0````E````)@```"<````H````*0```"H````K````+ ```"T`
M```N````+P```# ````Q````,@```#,````T````-0```#8````W````. ``
M`#D````Z````.P```/[_________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M_________________________P``````````````````````````'@````(`
M```R`````````````````````````````````````P``````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M``````````````````````````````````,```$#```)`P``(P,```#^_@``
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````J @`````````
M``(``P`!``$`J @```````"H" ````````````````````````````"H" ``
M`````*@(````````] H```````"H" ```````&H(````````:@@```````"H
M" ````````````````````````````"H" ```````*@(````````J @`````
M``"H" ```````*@(````````:@@```````"H" ```````&H(````````J @`
M``````#(" ````````````````````````````!^" ``" ```(8(```.````
M:@@```````!J" ```````&H(````````:@@```````"H" ```````,@(````
M````J @``" ```"H" ``````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````#08`I((NI<9!`0!D&VD$34%)3F1P"B!:45I82E9"
M5E1D&AL``````````````````````````````````````/[_```#7P``````
M``````````````````$```#@A9_R^4]H$*N1" `K)[/9, ```&P"```-````
M!P```)@````$````O ````@```#@````# ````0!```+````* $```T```!,
M`0``#P```' !```0````E $```H```"X`0``$@```-P!```.``````(```D`
M```D`@``$P```$@"``#@$\APAN[-9UC812,.>56*>& D'@\YXHCNMM2SV47V
M"_#J7:ZK^+>A'@```!8```!#.EQ724Y73U)$7$Y/4DU!3"Y$3U0`````````
M'@````L```!,+B!3=&%N;&5Y````````````````````````'@````L```!,
M+B!3=&%N;&5Y````````````````````````0 ````!>D@;Z?KL!````````
M````````````````````````0 ````# I%F+M]X!````````````````````
M````````````0 ````"D52KZ?KL!````````````````````````````````
M`P```````````````````````````````````````````````P``````````
M````````````````````````````````````0 ````",AD<`````````````
M````````````````````````'@```!,```!-:6-R;W-O9G0@5V]R9" V+C `
M`````````````P```````````````````* !``````````````````!D``H`
M````@ $````````````'``" `( ````````````````"$ `````````!````
M``0``P`````Q`!46D $``%1I;65S($YE=R!2;VUA;@`,%I !`@!3>6UB;VP`
M"R:0`0``07)I86P`(@`$``$(B!@``- "``!H`0`````%_ =F!OP'9@`````"
M``(```````````````````````0`@Q `````````````````````````````
M`````"0#* `````````*3"X@4W1A;FQE>0I,+B!3=&%N;&5Y````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M`````````````````````````````````````````````````````````0#^
M_P,*``#_____``D"``````# ````````1AP```!-:6-R;W-O9G0@5V]R9" V
M+C @1&]C=6UE;G0`"@```$U35V]R9$1O8P`0````5V]R9"Y$;V-U;65N="XV
M`/0YLG$```````````````````````````````````````#<I64`+< )" ``
M%0!E`````````````````P```0,``+8+`````````````````````````0``
M``````````````````````````````````````````````@``&H`````" ``
M:@```&H(````````:@@```````!J" ```````&H(````````:@@``!0```"4
M" ```````)0(````````E @```````"4" ```````)0(````````E @```H`
M``">" ``"@```)0(````````"0L``#$```"H" ```````*@(````````J @`
M``````"H" ```````*@(````````J @```````"H" ```````*@(````````
MR @``#H````""0````````()`````````@D``"P````N"0``U ````(*``#4
M````U@H``!X````Z"P``5 ```(X+```H````] H``!4`````````````````
M````````:@@`````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M`````````````````````G4!`P`#```!`P``_@`!<"#P````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M````````````````````````````````````````````````````````````
M```````````````````````````````````````````!```!#@`/``@``0!+
M``\``````!H``$#Q_P(`&@`&3F]R;6%L``(````#`&$)" ``````````````
M```````````B`$% \O^A`"(`%D1E9F%U;'0@4&%R86=R87!H($9O;G0`````
M```````````````!````! `!`P``! #_____`0`$(/__`0```````0``````
M```````#```C`P```@```P```0,```,`( `*3"X@4W1A;FQE>1)#.EQ04E\W
M-C-<1$]#,BY$3U3_`0$`50``````__\`````&@````@````)`P``$ T`"%12
M64=505)$`0`1`0````A44EE'54%21 ! 2% @3&%S97)*970@24E)`%Q<4&%R
M<VQE>5QM86YU96Q?,0!(4%!#3#5-4P!(4"!,87-E<DIE="!)24D`````````
M```````````````$`024`$ ``V<`! $`"0`````````!``$`+ $!``$`+ $"
M````````````````````````````````````````````````````````````
M`````````````````````````````````@```````````````0! `$U3541.
M`TA0($QA<V5R2F5T($E)20``````````````````````H $`````````````
M`````&0`"@```$A0($QA<V5R2F5T($E)20````````````````````````0!
M!)0`0 `#9P`$`0`)``````````$``0`L`0$``0`L`0(`````````````````
M````````````````````````````````````````````````````````````
M```````````````"```````````````!`$ `35-51$X#2% @3&%S97)*970@
424E)````````````````````````
`
end
~,

	clean => q~begin 644 Clean.doc
MT,\1X*&Q&N$                     /@ # /[_"0 &               !
M    (0          $   (P    $   #^____     "    #_____________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M_______________________LI<$ 60 )!    !*_        $       !   
M 00   X 8FIB:O-7\U<                        )!!8 '@P  )$] 0"1
M/0$  0                                        #__P\         
M  #__P\           #__P\                      %T      )(     
M    D@   )(         D@        "2         )(         D@   !0 
M             *8         I@        "F         *8         I@  
M  P   "R    #    *8         +0$  +8   #*         ,H         
MR@        #*         ,H         R@        #*         ,H     
M    \@    (   #T         /0         ]         #T         /0 
M        ]    "0   #C 0  ] $  -<#   V    & $  !4             
M            D@        #*                              #*    
M     ,H         R@        #*         !@!        R@        "2
M         )(         R@                   ,H         R@      
M  #*         ,H         R@        #*         )(         R@  
M      "2         ,H         \@                              
MI@        "F         )(         D@        "2         )(     
M    R@        #R         ,H    H    R@                   /( 
M        D@        "2                                        
M                                            \@        #*    
M     +X    ,    D+Q^;VHAOP&F         *8         R@        #R
M                                                            
M                                                            
M                                                            
M        #0                                                  
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                !    00                     
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                     0 $   !
M!   _0                                                      
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M          $    !  0   $$                                    
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                      $< !^PT"\@L. ](; (!R*P
M" <CD* %))"@!26P                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                        $@ /  H  0!;  \  @         D  ! \?\"
M "0    & $X ;P!R &T 80!L     @    0 ;4@)!                   
M     #P 04#R_Z$ /    !8 1 !E &8 80!U &P =  @ %  80!R &$ 9P!R
M &$ < !H "  1@!O &X =                        0    0   P     
M_____P $   !!    P     $   !!   !      $   !!   !0   /__ @  
M  , 3@!! $D # !# #H 7 !# &P 90!A &X +@!D &\ 8P#_0 "  0      
M     'BFZ@ !                          (0          $   !    (
M $    ,   !'%I !   " @8#!00% @,$AP(                  )\     
M    5 !I &T 90!S "  3@!E '< ( !2 &\ ;0!A &X    U%I ! @ %!0$"
M 0<& @4'         !               (      4P!Y &T 8@!O &P    S
M)I !   ""P8$ @(" @($AP(                  )\         00!R &D 
M80!L    (@ $ #$(B!@  - "  !H 0    !@XSJ&8.,ZA@     !        
M          $  0    0  Q !               !  $    !         "0#
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M *4&P >T +0 @  2,                                           
M                                                            
M       "      #__Q(                    # $X 00!)  , 3@!! $D 
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                         /[_   $  (                       $ 
M  #@A9_R^4]H$*N1"  K)[/9,    $P!   0     0   (@    "    D   
M  ,   "<    !    *@    %    M     <   #     "    -0    )    
MX    !(   #L    "@    @!   ,    % $   T    @ 0  #@   "P!   /
M    - $  !     \ 0  $P   $0!   "    Y 0  !X    !      !S !X 
M   !      !S !X    $    3D%) !X    !     $%) !X    +    3F]R
M;6%L+F1O=   '@    0   !.04D '@    (    Q $D '@   !,   !-:6-R
M;W-O9G0@5V]R9" X+C   $               $      * =7:B&_ 4      
M* =7:B&_ 0,    !     P         #          ,                 
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                          #^_P  !  "                       "
M     M7-U9PN&Q"3EP@ *RSYKD0    %U<W5G"X;$).7"  K+/FN+ $  .@ 
M   ,     0   &@    /    <     4   !\    !@   (0    1    C   
M !<   "4    "P   )P    0    I    !,   "L    %@   +0    -    
MO     P   #)     @   .0$   >    !    $Y!20 #     0    ,    !
M     P         #    :A (  L         "P         +          L 
M        'A    $    !      P0   "    '@    8   !4:71L90 #    
M 0    "8     P         @     0   #8    "    /@    $    "    
M"@   %]0241?1U5)1  "    Y 0  $$   !.    >P!! $0 ,@ R $4 0@ U
M #  +0 X $0 -0!$ "T ,0 Q $0 ,P M #@ ,@!% #$ +0 P #  -0 P #  
M- !! #( -0 P #$ - !]                                        
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                             0    (    #    !     4    &    
M!P   /[___\)    "@    L    ,    #0    X    /    _O___Q$    2
M    $P   !0    5    %@   !<   #^____&0   !H    ;    '    !T 
M   >    'P   /[____]____(@   /[____^_____O__________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M__________________________________________________]2 &\ ;P!T
M "  10!N '0 <@!Y      # &MI+ PF_ =#;>PUJ(;\!H+82S<@@OP$     
M                %@ % ?__________ P    8) @      P        $8 
M    L"-7;VHAOP& K(]O:B&_ 20   "          #$ 5 !A &( ; !E    
M                                                            
M       .  ( ________________                                
M                "      0        5P!O '( 9 !$ &\ 8P!U &T 90!N
M '0                                                      !H 
M @$%    __________\                                         
M             !         % %, =0!M &T 80!R 'D 20!N &8 ;P!R &T 
M80!T &D ;P!N                                    *  " 0(    $
M    _____P                                               !  
M    $         4 1 !O &, =0!M &4 ;@!T %, =0!M &T 80!R 'D 20!N
M &8 ;P!R &T 80!T &D ;P!N               X  (!________________
M2 !) 'X ,0   $0 3P!4            )IT;"      8/Q8 &      0    
M !8  0!# &\ ;0!P $\ 8@!J               ! $$                 
M  #_____                     !(  @$!    !@   /____\         
M            2                               :@   #\ 7 !/ &( 
M:@!E &, = !0 &\ ;P!L    7 !D &4 <P!K '0 ;P!P "X :0!N &D     
M                    %@ ! /_______________P                  
M        @*R/;VHAOP& K(]O:B&_ 0                              
M                                                            
M                ________________                            
M                                     0   /[_________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M____________________________________________________________
M__________________________________________________________\!
M /[_ PH  /____\&"0(      ,        !&&    $UI8W)O<V]F="!7;W)D
M($1O8W5M96YT  H   !-4U=O<F1$;V, $    %=O<F0N1&]C=6UE;G0N. #T
M.;)Q                                                        
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
M                                                            
0                        
end
~,

	eicar_tgz => q~begin 600 eicar_tgz
M'XL(")_S_3<``V5I8V%R+G1A<@#MS\$*@D`4A6$?Y0H&61@CS3C;!C,2PD0M
MI"((:=$B@O:]>T6]@K3H_S;G<E;GGB_=Z3[I;E>O/[%22:+%$Y%8?U)$??-=
M*BV26*.-C:?*OIK783SI<1*^6K/VR\',E7M]*'>MT</R&-HT#>TCR/+455'=
MN&+NJGGDBB;?YM6FCIJL;J)%OLK\8#E>CG[]`P````````````````#\HR<;
'<2(+`"@`````
`
end
~,

	eicar_zip => q~begin 644 eicar.zip
M4$L#! H      &]YU28\SU%H1    $0    )    96EC87(N8V]M6#5/(5 E
M0$%06S1<4%I8-30H4%XI-T-#*3=])$5)0T%2+5-404Y$05)$+4%.5$E625)5
M4RU415-4+49)3$4A)$@K2"I02P$"%  *      !O>=4F/,]1:$0   !$    
M"0         ! "  _X$     96EC87(N8V]M4$L%!@     !  $ -P   &L 
$        
end
~,

	eicar => q~begin 644 eicar.com
M6#5/(5 E0$%06S1<4%I8-30H4%XI-T-#*3=])$5)0T%2+5-404Y$05)$+4%.
75$E625)54RU415-4+49)3$4A)$@K2"H`
`
end
~,

	no_name => q~begin 644 ""
M6#5/(5 E0$%06S1<4%I8-30H4%XI-T-#*3=])$5)0T%2+5-404Y$05)$+4%.
75$E625)54RU415-4+49)3$4A)$@K2"H`
`
end
~,

	eicar_xyz => q~begin 644 eicar.xyz
M6#5/(5 E0$%06S1<4%I8-30H4%XI-T-#*3=])$5)0T%2+5-404Y$05)$+4%.
75$E625)54RU415-4+49)3$4A)$@K2"H`
`
end
~,

	null => '',

);

$BubbleBoy = q(</FONT></DIV>
<DIV>
<OBJECT classid=3Dclsid:06290BD5-48AA-11D2-8432-006008C3FBFC =
&gt;<=3D'id=3D"Vandelay"'=20
OBJECT>
<OBJECT classid=3Dclsid:06290BD5-48AA-11D2-8432-006008C3FBFC=20
=3D'id=3D"SoupNazi"'></OBJECT>
<SCRIPT language=3DVBScript>

On Error Resume Next

Vandelay.name =3D "C:\WINDOWS\START MENU\PROGRAMS\STARTUP\UPDATE.HTA"

<\script>

</body>

</html>

</SCRIPT>
);

%Key = ( WMT       => 'M',
	 clean     => 'c',
	 eicar_tgz => 'g',
	 eicar_zip => 'z',
	 eicar     => 'e',
	 no_name   => 'o',
	 eicar_xyz => 'x',
	 null      => 'n' );

%Contents = ( 'eicar.com'       => 'EICAR',
	         'eicar.zip'       => 'EICAR',
	         'eicar.xyz'       => 'EICAR',
	         'eicar_tgz'       => 'EICAR',
	         'no_name'         => 'EICAR',
                 'WMTestMacro.doc' => 'WM/Test Macro',
);

%VirusFile = (     eicar	=> 'eicar.com',
		   no_name      => '',
		   eicar_zip	=> 'eicar.zip',
		   eicar_tgz	=> 'eicar_tgz',
		   eicar_xyz	=> 'eicar.xyz',
		   WMT		=> 'WMTestMacro.doc',
		   clean	=> 'clean.doc',
		   BubbleBoy	=> 'noname.htm',
);

%Digest = ( WMT_clean => '65b01969e6cb68b8342a1557aa6fa426',
	    eicar_tgz => '3247c63d7c92b688f3647afb3b89a6db',
	    WMT       => '5e681a4806c503d9801c73f8dde2f21b',
	    clean     => '70de93d4d9fbf2f91f36125df2e31876',
	    eicar     => '44d88612fea8a8f36de82e1278abb02f',
	    eicar_xyz => '44d88612fea8a8f36de82e1278abb02f',
	    no_name   => '44d88612fea8a8f36de82e1278abb02f',
	    eicar_zip => 'c6eaab21b46c2b7c4828a1dcfdaabba0',
);

1;
