#!/usr/local/bin/perl -w

# get_hosts
# $Id: gethosts2,v 1.6 2005/11/15 18:08:55 larry Exp $  $Name:  $
# Collect hosts, trying very hard not to hit any more than once...

use strict;

use Net::hostent;
use IO::Socket;
use Socket;
use LWP::UserAgent;
use HTTP::Request;
use Getopt::Long;
use DB_File::Lock;
use Fcntl qw( :DEFAULT :flock );
use Errno "EAGAIN";
use POSIX qw( :sys_wait_h :signal_h WNOHANG);

use constant TMP           => "/tmp/gh$</";
use constant SOCK_PATH     => TMP . "hostserv";
use constant HOSTS_DB      => TMP . "hosts.db";
use constant NAMES_DB      => TMP . "names.db";
use constant IPS_DB        => TMP . "ips.db";
use constant LEVEL_DB      => TMP . "next_level.db";

mkdir TMP;

# Shouldn't need this, but we do
my $GH_Lockfile   = TMP . "gh_LOCK";

my $time_path     = TMP . "time";

$| = 1;
$SIG{CHLD} = \&REAPER;
$SIG{TERM} = $SIG{INT} = sub { exit 0 };

( my $ME = $0 ) =~ s@.*/@@;
my $USAGE = qq(USAGE: $ME [-h][-m max][ -p procs][-o out_file][-f in_file] [s0 s1 ..]\n);

#
# Options
#
my $max = 1000000;  # That's why it's an option. Right?
my $procs = 3;
my $out;
my $file;
my $help;
GetOptions( 'help' => \$help,
			'max=i' => \$max,
            'procs=i' => \$procs,
            'out=s'   => \$out,
            'file=s'    => \$file ) or die $USAGE;

if ( defined $out ) {
	if ( -f $out ) {
		print "Can't overwrite an existing file: $out.\n";
		exit 0;
	}
	open OUT, ">$out";
	select OUT;
}

if ( defined $help ) {
	die $USAGE;
}

#
# Priming the pump
#
unlink SOCK_PATH, HOSTS_DB, NAMES_DB, IPS_DB, LEVEL_DB, $time_path;

# The %host hash will contain the date which we dole out to the workers.
# Initially, the keys will just be a list of hostnames; after exhausting
# the starting list, the keys become a bit more complex containing both
# a hostname and the IPs for that host crammed into a string.
my @HOSTS;
if ( defined $file ) {
	die $USAGE if @ARGV;
	die qq(Can't read "$file": $!\n) unless -r $file;
	open IN, "<$file";
	@HOSTS = <IN>;
	close IN;
} elsif ( @ARGV ) {
	@HOSTS = @ARGV;
} else {
	@HOSTS = <DATA>;
}
chomp @HOSTS;
chomp( my @ary = <DATA> );
tie my %host, 'DB_File::Lock', HOSTS_DB, O_RDWR|O_CREAT, 0600, $DB_HASH, 'write';
@host{@HOSTS} = (1) x @HOSTS;
untie %host;

# This hash will contain the hostnames of the visited sites
tie my %visited_name, 'DB_File::Lock', NAMES_DB, O_RDWR|O_CREAT, 0600, $DB_HASH, 'write';
%visited_name = ();
untie %visited_name;

# This hash will contain the possible IPs for visited sites. The presence of
# an IP in the hash doesn't actually mean that the IP was visited, it simply
# means that it is one of the possible IPs for a visited sited.  Don't hit it.
tie my %visited_ip, 'DB_File::Lock', IPS_DB, O_RDWR|O_CREAT, 0600, $DB_HASH, 'write';
%visited_ip = ();
untie %visited_ip;

# This hash contains the data collected from the visited sites.  It is used
# to refill the pipeline; i.e., the %host hash
tie my %next_level, 'DB_File::Lock', LEVEL_DB, O_RDWR|O_CREAT, 0600, $DB_HASH, 'write';
%next_level = ();
untie %next_level;

#
# Spawn the workers...
#
my @pids;
my $ID = 0;
for ( 1 .. $procs ) {
	my $pid;
	$ID++;
	FORK:
	if ( $pid = fork ) {
		# I'm da boss!
		push @pids, $pid
	} elsif ( defined $pid ) {
		getem();
		exit 0;
	} elsif ( $! == EAGAIN ) {
		sleep 5;
		redo FORK;
	} else {
		die "Can't fork: $!\n";
	}
}

##########
# Main Process
##########
umask(0111);
open TIME, ">$time_path";
my $time = time;
print TIME "$time\n";
close TIME;
my $date = `date`;
print "Starting at $date";

my $listen = IO::Socket::UNIX->new( Local => SOCK_PATH, 
                                    Listen => SOMAXCONN ) or die "Socket: $!";

# Now we get set to fork a few more processes: we're going to be a forking server
while (1) {
	next unless my $connected = $listen->accept();
	die "Can't fork!" unless defined (my $child = launch_child());
	if ($child) {
		tie my %n, 'DB_File', NAMES_DB, O_RDONLY;
		if ( (my $total = keys %n) > $max ) {
			untie %n;
			print "\n#####\n## Have $total hosts; bailing out.\n#####\n";
			kill 9, @pids;
			sleep 5;
			unlink SOCK_PATH;
			untie %visited_name;
			untie %visited_ip;
			exit 0;
		}
		untie %n;
		push @pids, $child;
		close $connected;
	} else {
		close $listen;
		serve($connected);
		exit 0;
	}
}

#############################################################

sub launch_child {
  my $signals = POSIX::SigSet->new(SIGINT,SIGCHLD,SIGTERM,SIGHUP);
  sigprocmask(SIG_BLOCK,$signals);  # block inconvenient signals
  return unless defined (my $child = fork());
  unless ($child) {
    $SIG{$_} = 'DEFAULT' foreach qw(HUP INT TERM CHLD);
  }
  sigprocmask(SIG_UNBLOCK,$signals);  # unblock signals
  return $child;
}

sub serve {
	return unless my $c = shift;
	chomp $c;
	chomp (my $q = <$c>);
	my $me = $$;
	my %host;
	my %visited_name;
	my %visited_ip;
	my %next_level;
	my $host;
	if ( $q eq "gimme" ) {
		my @dead;
		# Belt and suspenders. Sigh.  It appears that DB_File::Lock can't
		# prevent simultaneous access, and neither does this, but it helps.
		open LOCK, ">$GH_Lockfile" or die "Can't open lockfile.\n";
		flock LOCK, LOCK_EX or die "Can't lock lockfile.\n";
		tie my %host, 'DB_File::Lock', HOSTS_DB, O_RDWR|O_CREAT, 0600, $DB_HASH, 'write'
			or die qq(Can't tie host db: $!);
		# $host is in the form:
		# hostname#ip,ip,ip
		HOST: while (my $h_ip = each %host ) {
			last unless $h_ip;
			# It's used up...
			push @dead, $h_ip;
			my ($name, $ips) = split /#/, $h_ip;
			tie %visited_name, 'DB_File::Lock', NAMES_DB, O_RDONLY, 0600, $DB_HASH, 'read'
				or die qq(Can't tie vis name: $!);
			next if $visited_name{$name};
			if ( $ips ) {
				tie %visited_ip, 'DB_File::Lock', IPS_DB, O_RDONLY, 0600, $DB_HASH, 'read'
					or die qq(Can't tie vis ip: $!);
				my @ips = split /,/, $ips;
				foreach my $ip ( @ips ) {
					next HOST if $visited_ip{$ip};
				}
			}
			$host = $name;
			last;
		}
		$host ||= "NONE";
		delete @host{@dead};
		my $host_count = keys %host;
		untie %host;
		untie %visited_name;
		untie %visited_ip;
		print $c $host;
		# If we've emptied the supply we need to replenish it before 
		# releasing our locks.
		unless ( $host_count ) {
			tie my %next_level, 'DB_File::Lock', LEVEL_DB, O_RDONLY, 0600, $DB_HASH, 'read'
				or die qq(Can't tie level: $!); 
			my $next_hosts = keys %next_level;
			untie %next_level;
			# We can't refill from %next_level unless somebody has put
			# something in it, so we'll just wait until they do.
			while ( not $next_hosts ) {
				sleep 5;
				tie my %next_level, 'DB_File::Lock', LEVEL_DB, O_RDONLY, 0600, $DB_HASH, 'read'
					or die "Can't tie level: $!\n";
				$next_hosts = keys %next_level;
				untie %next_level;
			}
			# Now we'll copy the collected hosts into the %host hash and
			# start over.
			tie %host, 'DB_File::Lock',HOSTS_DB, O_RDWR|O_CREAT, 0600, $DB_HASH, 'write'
				or die "host tie failed: $!";
			tie %next_level, 'DB_File::Lock', LEVEL_DB, O_RDONLY, 0600, $DB_HASH, 'write'
				or die qq(Can't tie level: $!);
			while (my ($k, $v ) = each %next_level ) {
				$host{$k} = $v;
			}
			untie %host;
			%next_level = ();
			untie %next_level;
		}
		close LOCK;
		exit 0;
	}

	elsif ( $q eq "hereyago" ) {
		my $string = <$c>;
		# The data is initially pipe separated; the first element is the
		# the visited host; the others are the collected hosts.
		chomp(my @ary = split /\|/, $string, 2);
		my ($visited, $visited_ips ) = split /#/, $ary[0];
		tie %visited_name, 'DB_File::Lock', NAMES_DB, O_RDWR|O_CREAT, 0600, $DB_HASH, 'write'
			or die qq(Can't tie name: $!);
		$visited_name{lc($visited)}++;
		my $total = keys %visited_name;
		untie %visited_name;
		tie %visited_ip, 'DB_File::Lock', IPS_DB, O_RDWR|O_CREAT, 0600, $DB_HASH, 'write'
			or die qq(Can't tie ip: $!);
		foreach my $visited_ip ( split /,/, $visited_ips ) {
			$visited_ip{$visited_ip}++;
		}
		untie %visited_ip;
		my @next = split /\|/, $ary[1] if $ary[1];
		HOST:
		foreach my $n ( @next ) {
			my ( $h, $ips ) = split /#/, $n;
			my @ips = split /,/, $ips;
			# we won't mark these as visited just yet
			tie %visited_name, 'DB_File::Lock', NAMES_DB, O_RDONLY, 0600, $DB_HASH, 'read'
				or die qq(Can't tie name: $!);
			next if $visited_name{lc($h)};
			untie %visited_name;
			tie %visited_ip, 'DB_File::Lock', IPS_DB, O_RDONLY, 0600, $DB_HASH, 'read'
				or die qq(Can't tie ip: $!);
			foreach my $ip ( @ips ) {
				next HOST if $visited_ip{$ip};
			}
			untie %visited_ip;
			tie %next_level, 'DB_File::Lock', LEVEL_DB, O_RDWR|O_CREAT, 0600, $DB_HASH, 'write'
				or die qq(Can't tie level: $!);
			$next_level{lc($n)}++;
			untie %next_level;
		}
		my $t1 = time;
		open TIME, "<$time_path";
		unless (flock(TIME, LOCK_SH | LOCK_NB)) {
			flock(TIME, LOCK_SH);
		}
		chomp (my $time = <TIME> );
		my $interval = $t1 - $time;
		if ( $t1 - $time > 9 ) {
			close TIME;
			sysopen( TIME, "$time_path", O_WRONLY | O_CREAT);
			flock(TIME, LOCK_EX);
			truncate(TIME, 0);
			print TIME "$t1\n";
			print "\n######\n## Total of $total hosts visited -- ", scalar localtime($t1), ".\n######\n\n"
		}
		close TIME;
		exit 0;
	} 
}

sub getem {
	my $host;
	my $me = $ID;
	my @USER_AGENTS = ("Mozilla/5.0 (Macintosh; U; PPC Mac OS X; en) AppleWebKit/416.11 (KHTML, like Gecko) Safari/416.12",
		"Mozilla/5.0 (compatible; Konqueror/3.4; Linux) KHTML/3.4.0 (like Gecko)",
		"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)",
		"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.7.8) Gecko/20050511 Firefox/1.0.4",
		"Mozilla/4.0 (compatible; MSIE 5.23; Mac_PowerPC)"
		);
		
	my $ua = LWP::UserAgent->new();
	my $agent = $USER_AGENTS[ int(rand(@USER_AGENTS))];
	$ua->agent($agent);
	$ua->timeout(30);
	
	$SIG{PIPE} = sub { exit 0; };
	my $sock;
	# Since the children were spawned before the server is set up, we'll
	# have to wait a bit, and we have to do it inside an eval loop.
	while ( not defined eval { $sock = IO::Socket::UNIX->new( SOCK_PATH ) } ) {
		sleep 1;
	}
	$| = 1;
	while ( 1 ) {
		print $sock "gimme\n";
		chomp( $host = <$sock>);
		$sock->close;
		# If the server couldn't get us a host he'll pass NONE.
		next unless $host and $host ne 'NONE';
		# This is to split apart the base host and any port designation.
		$host =~ s/(:\d+)$// and (my $port = $1) =~ s/^://;
		my $h;
		unless ($h = gethost( $host ) ){
			warn "[Proc $me] no such host: $host\n";
			next;
		}
		my $host_ips = join ",", map { inet_ntoa($_) } @{$h->addr_list};
		# Reassemble everything
		my $url = $host;
		$url = "http://" . $url unless $url =~ m@\Ahttp://@;
		$url .= ":$port" if $port;
		my $req; my $resp;
		$req = HTTP::Request->new(GET => $url);
		# GIFS?  We don't need no stinkin' GIFS!
		$req->header(Accept => 'text/*');
		$resp = $ua->request($req);
		$host .= ":$port" if $port;
		my $string = "$host#$host_ips|";	
		my %hosts;
		if ($resp->is_error() ) {
			next;
		} else {
			# Grab the page as a single string..
			my $content = $resp->content();
			# Pull all of the likely URLS into an array...
			my @tmp = $content =~ /http:\/\/(.*?)[^.:\-\w]/msg;
			# And pass the info back to main
			foreach my $tgt ( @tmp ) {
			# Process through
				$tgt = lc( $tgt );
				# This is somewhat redundant, but it may save some time
				# on the server end.
				next if $hosts{$tgt}++;
				(my $host = $tgt) =~ s/:\d+$//;
				next unless $h = gethost( $host );
				my $ips = join ",", map { inet_ntoa($_) } @{$h->addr_list};
				$string .= "$tgt#$ips|";
			}
		}
		$sock = IO::Socket::UNIX->new( SOCK_PATH ) or die "Socket: $!\n";
		next unless $string;
		print $sock "hereyago\n";
		print $sock "$string\n";
		$sock->close;
		print "Proc $me visited $host\n";
	} continue {
		$sock = IO::Socket::UNIX->new( SOCK_PATH ) or die "Socket: $!\n";
	}
}

sub REAPER {
	my $goner;
	while ($goner = waitpid(-1, &WNOHANG) > 0 ) {
	}
	$SIG{CHLD} = \&REAPER;
}

	
            
__DATA__
drudgereport.com
www.macsurfer.com
news.google.com
refdesk.com
www.ryukyushimpo.co.jp
mainportals.com
196.27.1.82
7am.com
a.tribalfusion.com
abcnews.go.com
aboutcity.com
adage.com
admin.kvasir.sol.no
adserver1-images.backbeatmedia.com
adserver1.backbeatmedia.com
albawaba.com
angelfire.com
aol.com.hk
ap.tbo.com
apennyfor.typepad.com
apnews.myway.com
appledumplings.com
arabul.dominet.com.tr
argentina.wwwdirectory.net
aroundcny.com
asia.yahoo.com
asiadragons.com
au.aol.com
austria.intersearch.net
big5.howhunt.com
biz.yahoo.com
bolivia.wwwdirectory.net
breakingnews.iol.ie
browserwatch.iworld.com
ca.yahoo.com
canadopedia.com
cantrek.com
cbc.ca
cbs.marketwatch.com
channels.netscape.com
china.asiaco.com
chinese.excite.com
cnn.com
comment.zdnet.co.uk
compass.net.edu.cn:8010
daily.stanford.edu
dailynews.yahoo.com
de.intersearch.net
dealmac.com
digester.et.tudelft.nl
dir.yahoo.com
directory.centramerica.com
docs.info.apple.com
download.cnet.com
edition.cnn.com
elindice.com
english.china.com
english.daralhayat.com
english.pravda.ru
finance.yahoo.com
findx.nikkeibp.co.jp
franceexport.com
free.netlap.hu
fresheye.com
gbchinese.yahoo.com
groups.google.com
guiden.no
headliner.net
hiptop.bedope.com
home.kyodo.co.jp
home.microsoft.com
home.netscape.com
homepage.mac.com
images.google.com
infolanka.com
inside.c-spanarchives.org:8080
interestalert.com
isl-garnet.uah.edu
italianwebspace.com
japan.infoseek.com
kbase.info.apple.com
kostenloses.com
kvasir.dk
launch.yahoo.com
lowendmac.com
ma.orientation.com
maccentral.macworld.com
macintosh.fryke.com
macreviewzone.com
macslash.org
macspeedzone.com
macteens.com
macvillage.net
maps.yahoo.com
mars.cropsoil.uga.edu
media.fastclick.net
meta.rrzn.uni-hannover.de
metromix.chicagotribune.com
mexico.web.com.mx
miner.uol.com.br
money.cnn.com
msnbc.msn.com
neti.ee
netindex.ist.utl.pt
netplaza.biglobe.ne.jp
news.bbc.co.uk
news.com.com
news.ft.com
news.harmony-central.com
news.myway.com
news.mywebpal.com
news.scotsman.com
news.yahoo.com
news.zdnet.co.uk
ns.analystonline.co.il
nypost.com
nzexplorer.co.nz
online.wsj.com
order.kagi.com
pccms.pku.edu.cn:8000
people.bulgaria.com
public.shns.com
pubs.acs.org
quote.bloomberg.com
quote.yahoo.com
ragno.plugit.net
sear.ch
search.asia.yahoo.com
search.ch
search.hk.com
search.mic.ro
search.newmalaysia.com
search.news.yahoo.com
search.sina.com.cn
searchireland.com
searchmalta.com
sfgate.com
sg.news.yahoo.com
sg.yahoo.com
sitesearch.washingtonpost.com
slashdot.org
slate.msn.com
slovakia.net
sourceforge.net
sports.espn.go.com
story.news.yahoo.com
swift.kerna.com
taiwan.asiaco.com
thecelebritycafe.com
thejapanfaq.cjb.net
ticovista.com
time.com
timesofindia.indiatimes.com
titan.mcnet.ne.jp
today.com.sg
translate.google.com
u.dailynews.com
uk.gay.com
us.news1.yimg.com
usinfo.state.gov
view.atdmt.com
w3.hitbox.com
w3.infoseek.de
walla.co.il
washingtonpost.com
web.de
weblist.ru
www.100hot.com
www.123india.com
www.163.com
www.180096hotel.com
www.21cn.com
www.2guysamacandawebsite.com
www.3.14159.com
www.aaa.com.au
www.abc.net.au
www.abcnews.com
www.about.com
www.abqtrib.com
www.accessnz.co.nz
www.achei.com.br
www.achla.co.il
www.adb.net
www.admcity.com
www.adonde.com
www.advalvas.be
www.afxpress.com
www.ahshun.com
www.aintitcool.com
www.ajc.com
www.aladin.de
www.alcanseek.com
www.aljazeerah.info
www.allesklar.de
www.altavista.co.kr
www.altavista.de
www.altavista.yellowpages.com.au
www.amazon.com
www.amconmag.com
www.anancyweb.com
www.anandtech.com
www.ananova.com
www.ananzi.co.za
www.andrewsullivan.com
www.anncoulter.org
www.anorak.co.uk
www.anzwers.co.nz
www.anzwers.com.au
www.aol.ca
www.aol.co.uk
www.aol.com
www.apollo7.de
www.aport.ru
www.apple-x.net
www.apple-zone.com
www.apple.com
www.applelinks.com
www.applelust.com
www.applematters.com
www.appleturns.com
www.appuonline.com
www.arabicnews.com
www.architosh.com
www.ariane6.com
www.ariannaonline.com
www.arkansasnbc.com
www.artus.com
www.asiadragons.com
www.asiansources.com
www.atpm.com
www.atrium.com
www.atrus.ru
www.austria-www.at
www.autoindustry.co.uk
www.axisoflogic.com
www.ba.net
www.bacan.com
www.bangkokpost.com
www.barefeats.com
www.bbc.co.uk
www.beijixing.com.cn
www.belgiumexports.com
www.best.sk
www.bgdailynews.com
www.big-bang.com
www.billboard.com
www.bizportal.co.il
www.bloomberg.com
www.bmwusa.com
www.bolivian.com
www.boliviaweb.com
www.boston.com
www.br.aol.com
www.bradesco.com.br
www.brujula.cl
www.bugzilla.com
www.bugzilla.org
www.bugzilla.net
www.buscame.com
www.buscapique.com
www.cade.com.br
www.canada.com
www.canadamalls.com
www.cancerfacts.com
www.canoe.ca
www.careersnet.com
www.cari.com.my
www.cbn.com
www.cbsnews.com
www.cernet.edu.cn
www.cheaptickets.com
www.chevere.com
www.chicagotribune.com
www.chile-online.com
www.chilebusca.cl
www.chilnet.cl
www.china-on-site.com
www.chinaburst.com
www.chinapage.com
www.chinapages.com
www.chinascape.org
www.chinattic.com
www.chinavista.com
www.chinawebs.com
www.chinese.com
www.chron.com
www.cis.com.cn
www.cmug.org
www.cnet.com
www.cnn.com
www.comics.com
www.computerworld.com
www.conexcol.com
www.connected.telegraph.co.uk
www.counterpunch.org
www.cq.com
www.creativemac.com
www.creators.com
www.cseek.com
www.csmonitor.com
www.ctv.ca
www.cubaweb.cu
www.cube-zone.com
www.cusco.pt
www.cypria.com
www.cyprus2000.com
www.dailyemerald.com
www.dailynewslosangeles.com
www.dailyrecord.co.uk
www.danny.com
www.data.ru
www.dealsontheweb.com
www.denverpost.com
www.dfw.com
www.dice.com
www.digitmag.co.uk
www.dino-online.de
www.dir.bg
www.dirbg.com
www.dpmac.com
www.dragon.co.jp
www.drudgereportarchives.com
www.dstc.edu.au
www.dubai-online.com
www.dw-world.de
www.eagleforum.org
www.ebay.com
www.ecila.fr
www.economist.com
www.editorandpublisher.com
www.edmunds.com
www.edsa.com.ph
www.ee
www.efenews.com
www.egyptsearch.com
www.egyptside.com
www.elsalvador-sv.com
www.emergency.com
www.eule.de
www.eurekalert.org
www.euronet.nl
www.eurosoft.bg
www.everyday.se
www.evreka.com
www.excite.com
www.excite.de
www.expedia.com
www.explore-mex.com
www.export.gov.il
www.express.co.uk
www.fareast.ru
www.fast.ro
www.faz.com
www.fedex.com
www.fi
www.fireball.de
www.fixx.de
www.folklore.org
www.fool.com
www.forbes.com
www.foxnews.com
www.fr.msn.com
www.france.aol.com
www.francite.fr
www.freep.com
www.fresnobee.com
www.ft.com
www.gamedb.com
www.gaseste.com
www.geek.com
www.geekculture.com
www.geo.net.co
www.geocities.com
www.georgewbush.com
www.germany.aol.com
www.gertzfile.com
www.globalirish.com
www.globeandmail.com
www.globes.co.il
www.go.com
www.gogreece.com
www.goldenvillage.com
www.goldfish.com
www.golfdiscount.com
www.golf.com
www.google.com
www.goyoyo.cq.cn
www.gr-indexer.gr
www.great-british-pages.co.uk
www.grippo.com
www.guardian.co.uk
www.guegue.com.ni
www.guidegozo.com
www.gyuvet.ch
www.hardmac.com
www.healthcentral.com
www.healthday.com
www.heraldsun.news.com.au
www.heureka.hu
www.hillnews.com
www.hispavista.com
www.historychannel.com
www.hitbox.com
www.hkseek.com
www.hollywood.com
www.hollywoodreporter.com
www.holms.ru
www.home2000.com.cn
www.homekids.com
www.hongen.com
www.hotmail.com
www.howhunt.com
www.hudir.hu
www.hugmot.is
www.humaneventsonline.com
www.iboom.com
www.idevgames.com
www.iearthbound.com
www.iesearch.ie
www.iht.com
www.iit.edu
www.ilse.nl
www.imdb.com
www.in-honduras.com
www.independent.co.uk
www.indiaconnect.com
www.indianindex.com
www.indiasearchengine.com
www.indoseek.co.id
www.indystar.com
www.inetg.com
www.info.co.cr
www.infocop.com
www.infoguiaweb.com
www.infospace.com
www.ingrid.org
www.insanely-great.com
www.insanelygreatmac.com
www.insidemacgames.com
www.insightmag.com
www.intermarkets.net
www.interservegypt.com
www.intworkshop.com
www.investors.com
www.iol.co.il
www.iol.it
www.ipclub.ru
www.ipod-zone.com
www.ipodhacks.com
www.ipodhead.com
www.ipodlounge.com
www.ipoinc.com.hk
www.irna.com
www.isize.com
www.iskin.com
www.islandtel.com
www.itv.com
www.itweb.co.za
www.iviet.com
www.jadoo.com
www.jamaica-gleaner.com
www.jargon.net
www.jewishworldreview.com
www.jp.aol.com
www.jpost.com
www.jubii.dk
www.junkscience.com
www.kaleo.org
www.kausfiles.com
www.kcna.co.jp
www.kenstone.net
www.khoj.com
www.kompass.ie
www.kor-seek.com
www.korea.com
www.kufta.com
www.kuwaitonline.com
www.lafcpug.org
www.lankaonline.com
www.lasvegassun.com
www.latimes.com
www.latinol.com
www.laweekly.com
www.le-guide.com
www.lebanon2000.com
www.lebanonlinks.net
www.lebhost.com.lb
www.lebseek.com
www.leti.no
www.libanis.com
www.list.ru
www.lucianne.com
www.luxpoint.lu
www.luxweb.lu
www.lycos.co.jp
www.lycos.com
www.maariv.co.il
www.mac-upgrade.com
www.macactually.com
www.macaddict.com
www.macblog.com
www.macbuyersguide.com
www.macdailynews.com
www.macdesignonline.com
www.macdirectory.com
www.macedition.com
www.macevangelist.com
www.macfixit.com
www.macgamefiles.com
www.macgamer.com
www.machome.com
www.macinstein.com
www.macintouch.com
www.macjams.com
www.macmall.com
www.macmerc.com
www.macminute.com
www.macmothership.com
www.macnet2.com
www.macnightowl.com
www.macnn.com
www.macnyt.dk
www.macobserver.com
www.maconlysource.com
www.macopinion.com
www.macorchard.com
www.macosplanet.com
www.macosrumors.com
www.macosxhints.com
www.macpicks.com
www.macresource.com
www.macreview.com
www.macreviewzone.com
www.macscripter.net
www.macseek.com
www.macshareware.net
www.macslash.org
www.macsonly.com
www.macspeedzone.com
www.mactech.com
www.macteens.com
www.mactipsandtricks.com
www.macuarium.com
www.macupdate.com
www.macuser.co.uk
www.macwindows.com
www.macworld.co.uk
www.macworld.com
www.macwrite.com
www.mainportals.com
www.malaysia-index.com
www.malaysiasearch.com
www.malcolmadams.com
www.maltanetworkresources.com
www.manoramaonline.com
www.maplesquare.com
www.maroc.net
www.masnet.org
www.max.co.za
www.medialifemagazine.com
www.mediamac.dk
www.mediaresearch.org
www.mediaweek.com
www.megastar.co.uk
www.mercurynews.com
www.metabusca.com
www.metacrawler.com
www.mexonline.com
www.miami.com
www.microsoft.com
www.middle-east-online.com
www.middle-east-pages.com
www.militarycity.com
www.mirror.co.uk
www.mlive.com
www.mobilepipeline.com
www.monaco.mc
www.monster.com
www.moviepoopshoot.com
www.mrbarrett.com
www.msn.co.il
www.msnbc.msn.com
www.msu.mcmaster.ca
www.muchmusic.com
www.mugcenter.com
www.my-kuwait.com
www.myapplemenu.com
www.mymac.com
www.myrice.com
www.nana.co.il
www.nakhonpathom.com
www.nationalenquirer.com
www.nationalreview.com
www.netc.pt
www.netease.com
www.netguide.ch
www.netking.co.il
www.neto.co.il
www.netscape.com
www.netsearchjamaica.com
www.news24.com
www.newsbytes.com
www.newscientist.com
www.newsday.com
www.newseum.org
www.newsoftheworld.co.uk
www.newsweek.com
www.newyorker.com
www.nexosur.com
www.niceone.com
www.nihon.net
www.niweb.com
www.nl-menu.nl
www.nomade.fr
www.npr.org
www.nydailynews.com
www.nypost.com
www.nytimes.com
www.observer.com
www.officialspin.com
www.ole.es
www.omania.net
www.onelook.com
www.oneworld.org
www.online.bg
www.online.ie
www.oomph.net
www.opensource.org
www.opinionjournal.com
www.oreillynet.com
www.origo.hu
www.osnews.com
www.osopinion.com
www.osx-zone.com
www.osxfaq.com
www.osxzone.com
www.ozsearch.com.au
www.ozu.net
www.pa
www.palmbeachpost.com
www.passagen.se
www.pathfinder.com
www.pbs.org
www.pbsource.com
www.pbzone.com
www.pcweenies.com
www.pcworld.com
www.people.com
www.peru-info.com
www.peruonline.com
www.phantis.com
www.philly.com
www.piranha.com.ve
www.planet.nl
www.polishworld.com
www.powerbookcentral.com
www.powerpage.org
www.pricewatch.com
www.prnewswire.com
www.pww.org
www.qatar-info.com
www.qis.net
www.radar.com.ar
www.radioandrecords.com
www.rainbownetwork.com
www.rambler.ru
www.rampantscotland.com
www.rank.stars.ru
www.rbg.kew.org.uk
www.readchina.com
www.reasonmag.com
www.redskins.com
www.reduy.com
www.rekha.com
www.resexcellence.com
www.reuters.co.uk
www.reuters.com
www.richardreeves.com
www.rightonmac.com
www.riscx.com
www.robby.gr
www.rockymountainnews.com
www.rol.ro
www.rollcall.com
www.ru
www.rucity.com
www.rushlimbaugh.com
www.saabusa.com
www.sabay.com
www.sacbee.com
www.salon.com
www.santacruzsentinel.com
www.sanook.com
www.saudi-pages.com
www.saudiarabia.net
www.sciam.com
www.scotland.com
www.scotland.net
www.se.archangelsk.ru
www.seacoastonline.com
www.search.bg
www.search.centre.ru
www.search.nl
www.searchchina.com
www.searchindia.com
www.searchingireland.com
www.searchnz.co.nz
www.searchsingapore.com
www.searchuk.com
www.seznam.cz
www.sfgate.com
www.signonsandiego.com
www.sitelink.net
www.sky.com
www.slate.com
www.sltrib.com
www.smh.com.au
www.sobran.com
www.sofcom.com
www.sohoo.com.cn
www.sol.es
www.southafrica.co.za
www.speedfind.de
www.sportinglife.com
www.spray.se
www.spymac.com
www.starmagazine.com
www.startpagina.nl
www.startribune.com
www.stepwise.com
www.stockpickreport.com
www.stop.hu
www.stpt.com
www.stuff.co.nz
www.stuffmagazine.co.uk
www.sunet.se
www.sun.com
www.suntimes.com
www.supermall.co.il
www.surf-bits.com
www.surfchina.com
www.surfindia.com
www.surok.wolf.ru
www.svnet.org.sv
www.sympatico.ca
www.syracuse.com
www.tapuz.co.il
www.technn.com
www.techtree.com
www.tela.dux.ru
www.telegraph.co.uk
www.terere.com
www.thailand.com
www.theage.com.au
www.theaustralian.news.com.au
www.thebostonchannel.com
www.theimac.com
www.theinquirer.net
www.themacmind.com
www.themilitant.com
www.thenation.com
www.thenewrepublic.com
www.thesaurus.com
www.thestatesman.net
www.thestreet.com
www.thesun.co.uk
www.thetimes.co.uk
www.theultimates.com
www.thinksecret.com
www.thisislondon.com
www.tibetinfo.net
www.tidbits.com
www.time.com
www.timesonline.co.uk
www.tjohoo.se
www.townhall.com
www.tribnet.com
www.tucows.com
www.turkvista.com
www.tvguide.com
www.tvinsite.com
www.tvspy.com
www.tvweek.com
www.uae-pages.com
www.uaetoday.com
www.uexpress.com
www.ukplus.com
www.ukrania.com
www.ulitka.ru
www.unitedhellas.com
www.upgo.com
www.upi.com
www.ups.com
www.uruguay.org.uy
www.usatoday.com
www.usnews.com
www.usnewswire.com
www.usps.gov
www.utopia.co.nz
www.vw.com
www.vefur.is
www.versiontracker.com
www.vietgate.net
www.vietpage.com
www.villagevoice.com
www.vinaone.com
www.virgilio.it
www.virtualisimo.com
www.virtualvin.com
www.voanews.com
www.voila.co.uk
www.voila.fr
www.w3.org
www.wane.com
www.washingtonpost.com
www.washingtontimes.com
www.washtimes.com
www.weather.com
www.webbel.be
www.webguidechina.com
www.webguiden.dk
www.webindex.gr
www.webito.com
www.webstudio.fi
www.webwatch.be
www.weeklystandard.com
www.whitehouse.gov
www.whiterabbits.com
www.whythemacissogreat.com
www.wired.com
www.wnd.com
www.workingmac.com
www.worldnetdaily.com
www.wow.pl
www.wp.pl
www.wstm.com
www.wvec.com
www.xhanubis.com
www.xlr8yourmac.com
www.xxl.ee
www.yagua.com
www.yahoo.co.jp
www.yahoo.co.uk
www.yahoo.com
www.yahoo.com.au
www.yahoo.de
www.yahoo.es
www.yahoo.fr
www.yahoo.it
www.yahoo.kts.ru
www.yahoo.se
www.yam.com.tw
www.yandex.ru
www.yazsoft.com
www.yehey.com
www.yifan.com
www.ynet.co.il
www.yoodle.ch
www.yourmaclife.com
www.zeek.com.br
www.zehuze.co.il
www.zhaodaola.com
www.zmije.cz
www.zoek.nl
www.zoznam.sk
www.zwire.com
www1.hiway.gr
www3.cjad.com
yahoo.businessweek.com
yep.com
zdnet.com.com
