#!/bin/bash

# $Id: chk_cores,v 1.10 2013/12/21 01:14:59 larry Exp $
# Check for core files on a list of hosts

while getopts 'bBqsvx:' OPTION
do
    case $OPTION in
    x)    EXCLUDE="$EXCLUDE $OPTARG"
        ;;
    s)    SHOW=1
        ;;
    v)    FULL=1
        ;;
    q)    QUIET=1
    	;;
    b)    BUILDOUT=1
        ;;
    B)    BUILDOUT2=1
        ;;
    h|?)  echo "Valid options are '-x exclude', '-v' all, '-s' show hosts, '-q' quiet, and '-b' use alternate file."
          exit 0
        ;;
    esac
done
shift $(($OPTIND - 1))

HOSTS=$@

if test -z "$HOSTS"
then
    HOSTLIST="hostlist"
    if [ "$BUILDOUT" ]
    then
        HOSTLIST="slist"
    elif [ "$BUILDOUT2" ]
    then
        HOSTLIST="blist2"
    fi
    . ~/lib/$HOSTLIST
fi

for NOT in $EXCLUDE
do
	HOSTS=${HOSTS/ $NOT / }
done

if [ "$SHOW" ]
then
    echo "Hosts: $HOSTS"
    exit 0
fi

if [ -n "$FULL" ]
then
	for host in $HOSTS
	do echo "=====> $host"
	if [[ ${host} == *:* ]] 
	then
		OPT="-6"
	else
		OPT=""
	fi
	if [[ $host =~ ^[[:digit:]]{3}$ ]]
	then
	   host=192.168.0.${host}
	fi
	ssh $OPT root@$host 'uname -n
	. /etc/sf/ims.conf
		COMMON=$SF_ROOT_PATH/var/common
		FILE=$ETC_PATH/PM.conf
			grep -q "core;" $FILE
		if [ $? -ne 0 ]*
		then
			echo
			echo "       >>>>>>>> Cores not turned on"
			echo
			next
		fi
			grep -q "/var/log/SFD.log" $FILE
		if [ $? -ne 0 ]*
		then
			echo
			echo "       >>>>>>>> SFD logging not turned on"
			echo
		fi
		
		if [ -d $COMMON ]
		then
			cd $COMMON
			for file in $(ls -tr core[._]*); do ls -ld --full-time $file; file $file; done 
			echo
		fi
	'; done 2>/dev/null
	echo
elif [ -n "$QUIET" ]
then
	for host in $HOSTS
	do
	if [ ${host:0:5} == "2001:" ] 
	then
		OPT="-6"
	else
		OPT=""
	fi
	if [[ $host =~ ^[[:digit:]]{3}$ ]]
	then
	   host=192.168.0.${host}
	fi
	ssh $OPT root@$host '
	. /etc/sf/ims.conf
	COMMON=$SF_ROOT_PATH/var/common
	cd $COMMON
	TMP="/tmp/cl$$"
	(for file in $(ls -tr core[._]*); do ls -ld --full-time $file; file $file; done) > $TMP
	if [ -s $TMP ]
	then
		echo "=====> $(hostname)"
		cat $TMP
		echo
	fi
	'; done 2>/dev/null
	echo
else
	for host in $HOSTS
	do echo "=====> $host"
	if [ ${host:0:5} == "2001:" ] 
	then
		OPT="-6"
	else
		OPT=""
	fi
		if [[ $host =~ ^[[:digit:]]{3}$ ]]
	then
	   host=192.168.0.${host}
	fi
	ssh $OPT root@$host 'uname -n
	. /etc/sf/ims.conf
	COMMON=$SF_ROOT_PATH/var/common
	FILE=$ETC_PATH/PM.conf
	grep -q "/var/log/SFD.log" $FILE
	if [ $? -ne 0 ]*
	then
		echo
		echo "       >>>>>>>> SFD logging not turned on"
		echo
	fi
	cd $COMMON
	COUNT=$(ls core[._]* | wc -l)
	if [ 5 -lt $COUNT ]*
	then
		echo "=============================================================================="
		echo "+++++++++++++++++++++++ Found ${COUNT// /} cores in /var/common ++++++++++++++++++++++++"
		echo "=============================================================================="
		echo
	else
		for file in $(ls -tr core[._]*); do ls -ld --full-time $file; file $file; done 
		echo
	fi
	'; done 2>/dev/null
fi
