#!/bin/bash

# $Id: csetup,v 1.3 2013/05/07 09:51:25 larry Exp $
/Users/larry/bin/setRoot weaver

HL=$(ssh weaver "mysql --skip-column-names -padmin sfsnort -e 'select ip from EM_peers where active = 1 and role = 2'" 2>/dev/null | tr -s '\012' ' ');

echo "HOSTS=\" weaver oates $HL \"" > /Users/larry/lib/blist
/Users/larry/bin/setRoot $HL
