#!/bin/bash

# $Id: csetup,v 1.2 2013/08/30 16:16:48 lprall Exp $
/nfs/home/lprall/bin/setRoot weaver
/nfs/home/lprall/bin/.setRoot weaver

HL=$(ssh weaver "mysql --skip-column-names -padmin sfsnort -e 'select ip from EM_peers where active = 1 and role = 2'" 2>/dev/null | tr -s '\012' ' ');

echo "HOSTS=\" weaver oates $HL \"" > /nfs/home/lprall/lib/blist
/nfs/home/lprall/bin/setRoot $HL
