#!/bin/bash

# $Id: set_cores.sh,v 1.17 2010/04/23 11:24:23 larry Exp $
# Turn on cores and SFDataCorrelator debugging on a list of hosts
# Set up logrotate for the debug files

EXCLUDE=""

while getopts 'shx:' OPTION
do
    case $OPTION in
    s)    SHOW=1
        ;;
    x)    EXCLUDE="$EXCLUDE $OPTARG"
        ;;
    h|?)  echo "Valid options are:"
          echo "  -x exclude_host" 
          echo "          Exclude this host; can be used multiple times." 
          echo "  -s" 
          echo "          Show list of hosts to be acted upon." 
          exit 0
        ;;
    esac
done
shift $(($OPTIND - 1))
HOSTS=$@

if test -z "$HOSTS"
then
. ~/lib/hostlist
fi

for NOT in $EXCLUDE
do
HOSTS=${HOSTS/ $NOT / }
done

if [ "$SHOW" ]
then
	echo "Hosts: $HOSTS"
	exit 0
fi

for host in $HOSTS; do echo "=====> $host";
scp ~/lib/SFD.logrotate root@$host:/etc/logrotate.d/ > /dev/null 2>&1
ssh root@$host 'uname -n
. /etc/sf/ims.conf
FILE=$SF_ETC_ROOT_PATH/etc/sf/PM.conf
grep -q "logfile /var/log/SFD.log;" $FILE
if [ $? -ne 0 ]
then
	/bin/ed $FILE <<-EOF
	/option --nodaemon/a
	    option --debug;
	    logfile /var/log/SFD.log;
	.
	wq
	EOF
	$SF_ETC_ROOT_PATH/etc/rc.d/init.d/pm restart > /dev/null
fi
'; done 2>/dev/null
