#!/bin/sh

# $Id: setvim,v 1.3 2009/01/14 21:50:53 larry Exp $ turn off stupid VIM args

HOSTS=$@

if test -z "$HOSTS"
then
HOSTS="csi sato glory kiesa entourage barret firman lightning2 lorne ocean12 eko xander ocean11 fightclub klitschko cuttingclass beingjohn";
fi

for host in $HOSTS
do

scp /Users/larry/.vimrc $host:.vimrc 2>/dev/null && echo Copied to $host

done

