#!/opt/local/bin/expect

# $Id: setRoot,v 1.4 2010/09/29 13:23:19 larry Exp $

foreach host $argv {
	# Have to get in as 'admin' first, then get a root shell
	spawn ssh "admin@$host"
	expect "Password:"
	send "Sourcefire\r"

	#  Might be a CLI box, so we have to get to expert mode first, then to root
	expect "> " { send "expert\r" }

	expect "admin@"
	send "sudo -i\r"
	#  This is conditional because sudo might have been run recently enough not
	#  to need a password
	expect "Password:" { send "Sourcefire\r" }
	expect "root@"

	send "perl -pi -e 's/PermitRootLogin no/PermitRootLogin without-password/' /etc/ssh/sshd_config /usr/local/sf/htdocs/templates/html_templates/pam/sshd_config.tt /usr/local/sf/htdocs/html_templates/pam/sshd_config.tt /usr/local/sf/htdocs/localization/en_US/templates/html_templates/pam/sshd_config.tt\r"
	expect "root@"

	send "/etc/rc.d/init.d/sshd restart\r"
	expect "root@"
	send "scp larry@10.5.45.18:.ssh/authorized_keys .ssh/authorized_keys\r"
	expect "connecting (yes/no)?" { send "yes\r" }
	expect "password:" { send "larry\r" }
	expect "root@"
	send "ls -l /boot > /root/boot.txt\r"
	expect "root@"
	send "cat /root/boot.txt\r"
	expect "root@"
	send "exit\r"
	# Again have to account for the possibility of a CLI box
	expect "admin@" { send "exit\r" }
	expect "> " { send "exit\r" }
	puts "\n"

}
