#!/opt/local/bin/expect

# $Id: setRoot,v 1.3 2010/09/24 18:14:50 larry Exp $

# Have to get in as 'admin' first, then get a root shell
spawn ssh "admin@$argv"
expect "Password:"
send "Sourcefire\r"

#  Might be a CLI box, so we have to get to expert mode first, then to root
expect "> " { send "expert\r" }

expect "admin@"
send "sudo -i\r"
#  This is conditional because sudo might have been run recently enough not
#  to need a password
expect "Password:" { send "Sourcefire\r" }
expect "root@"

send "perl -pi -e 's/PermitRootLogin no/PermitRootLogin without-password/' /etc/ssh/sshd_config /usr/local/sf/htdocs/templates/html_templates/pam/sshd_config.tt /usr/local/sf/htdocs/html_templates/pam/sshd_config.tt /usr/local/sf/htdocs/localization/en_US/templates/html_templates/pam/sshd_config.tt\r"
expect "root@"

send "/etc/rc.d/init.d/sshd restart\r"
expect "root@"
send "exit\r"
# Again have to account for the possibility of a CLI box
expect "admin@" { send "exit\r" }
expect "> " { send "exit\r" }
puts "\n"


