#!/bin/sh
# Must run as root rather than as arg to sudo; do 'sudo -s', then run
# This rather awkward procedure is so that we can get full pathnames in the output.
# The awk print statement makes some assumptions.
/usr/bin/find / -print0 | /usr/bin/xargs -0 /bin/ls -ldo 2>/dev/null  | awk ' $0 ~! /^ *$/ && $0 !~ /:$/ && $0 !~ /^total/ && $5 != "-" { print $5, $10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20 } '

